name: valeincorp
description: Aplicativo Valeincorp - ImÃ³veis e Empreendimentos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Media
  video_player: ^2.8.2
  photo_view: ^0.14.0
  
  # Maps
  google_maps_flutter: ^2.5.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  
  # Utils
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  cross_file: ^0.3.4
  mask_text_input_formatter: ^2.7.0
  intl: ^0.19.0
  
  # PDF
  flutter_pdfview: ^1.3.2
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Image picker
  image_picker: ^1.0.7
  
  # Path provider
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

